services:
  flutter-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - .:/app
    environment:
      - FLUTTER_STORAGE_BASE_URL=https://storage.googleapis.com