services:
  flutter-app:
    build:
      context: .
      dockerfile: Dockerfile
<<<<<<< HEAD
    container_name: flutter_app_container
    ports:
      - "8090:80"  # Porta per il servizio Flutter (da configurare a seconda delle tue necessità)

  nginx:
    image: nginx:alpine
    container_name: nginx_container
=======
>>>>>>> 7bf994c400af9b3d98bcc29f9dea2619e6ef2ea3
    ports:
      - "8080:80"  # Porta per il server Nginx
    volumes:
<<<<<<< HEAD
      - ./build/web:/usr/share/nginx/html  # Monta il build della tua app Flutter nella cartella nginx
    depends_on:
      - flutter-app  # Assicura che il container flutter-app venga avviato prima di nginx

volumes:
  flutter-web:
    external: true  # Se vuoi usare un volume persistente, puoi definirlo così
=======
      - .:/app
    environment:
      - FLUTTER_STORAGE_BASE_URL=https://storage.googleapis.com
>>>>>>> 7bf994c400af9b3d98bcc29f9dea2619e6ef2ea3
