services:
  flutter-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flutter_app_container
    ports:
      - "8090:80"  # Porta per il servizio Flutter 

  nginx:
    image: nginx:alpine
    container_name: nginx_container
    ports:
      - "8080:80"  # Porta per il server Nginx
    volumes:
      - ./build/web:/usr/share/nginx/html  # Monta il build della app Flutter nella cartella nginx
    depends_on:
      - flutter-app  # Assicura che il container flutter-app venga avviato prima di nginx

volumes:
  flutter-web:
    external: true  # Utilizzo di un volume persistente
