services:
  flutter-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flutter_app_container
    ports:
      - "8090:80"

  nginx:
    image: nginx:alpine
    container_name: nginx_container
    ports:
      - "8080:80"
    volumes:
      - ./build/web:/usr/share/nginx/html
    depends_on:
      - flutter-app

volumes:
  flutter-web:
